#  数据源和连接池
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${blog.database.pgsql.host}:${blog.database.pgsql.port}/w_blog
    username: ${blog.database.pgsql.username}
    password: ${blog.database.pgsql.password}
    hikari:
      maximum-pool-size: 17
      minimum-idle: 17
  data:
    redis:
      host: ${blog.database.redis.host}
      port: ${blog.database.redis.port}
      password: ${blog.database.redis.password}