spring:
  mail:
    host: ${blog.mail.host}
    username: ${blog.mail.username}
    password: ${blog.mail.password}
    protocol: ${blog.mail.protocol}
    port: ${blog.mail.port}
    test-connection: ${blog.mail.test-connection}