database:
  pgsql:
    username: test
    password: ENC(nghQaxCXJnoZg2VxyfogaEspwzijrMXh)
    host: localhost
    port: 5432
  redis:
    password: ENC(3fXZ7ozGdD/WYUUoxK7y7XBf/mG8kyvq)
    host: localhost
    port: 6379


